### ISSUE TITLE
The command list doesn't disappear automatically after executing command "Azure Container Apps: Open Logs in Portal" from command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurecontainerapps#194]
**OS:** All
**Build Version:** 20220912.2

**Repro Steps:**
1. F1 -> Azure Container Apps: Open Logs in Portal -> Select a resource -> Select a container app -> Select "Logs" -> Select log view.
2. Check whether the command list disappears automatically.

**Expect:**
The command list disappears automatically.

**Actual:**
The command list doesn't disappear automatically.
![image](https://user-images.githubusercontent.com/57662131/189838791-9bba62ac-c050-4fa9-a2b6-e3c3cd660392.png)

**More Info:**
This issue doesn't reproduce when executing other commands from command palette.

**Comment by MicroFish91** [comment]
Ahh, this is happening because the `LogsTreeItem` has a `commandId` attached to it that is being run automatically when we pick the node through the `command palette`.  We will need to revisit this sort of behavior in the next revision of the picker API.  

Idea:  Maybe we allow an optional flag we can set to override auto running of the `commandId` for instances like this

**Comment by alexweininger** [comment]
We should be picking a container app, and then showing a separate quick pick for selecting between Open Logs and Open Log Stream.
