### ISSUE TITLE
The opened web page is still for quickstart image after deploying a different image to the container app

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#298]
**OS:** Win 10
**Build Version:** 20230323.1
**Regression:** Not a Regression

**Repro Steps:**
1. Create one container app with "Use quickstart image" selected.
2. Right click this new created container app and execute "Deploy to Container App..." action with an existing different image (such as express). 
3. Click "Browse" button in the below notification.
![image](https://user-images.githubusercontent.com/45614674/227477808-5b97e6eb-4c8e-454e-b3ab-4d9f58b0653a.png)
4. Check whether the opened web page is for express image.

**Expect:**
The opened web page is for express image.
![image](https://user-images.githubusercontent.com/45614674/227480394-75404fc8-3256-459b-b801-d06a64523d25.png)

**Actual:**
The opened web page is still for quickstart image.
![image](https://user-images.githubusercontent.com/45614674/227478515-ba0aedc4-d142-46ef-8085-d0875848bc6a.png)

**Comment by MicroFish91** [comment]
Which image source are you choosing after issuing `Deploy to Container App...`?

![image](https://user-images.githubusercontent.com/40250218/227690383-90d61e15-a7a8-43f7-8051-8a4d16532272.png)

**Comment by v-ruizh** [comment]
I selected the "Use existing image" resource to deploy an express image.

**Comment by MicroFish91** [comment]
Can you check to see what port number your latest image needs exposed?  This sounds like it could be a port number mismatch.  The quickstart image exposes port 80 by default.  If your current image needs a different port number exposed, you will need to `Edit target port..` under Ingress so that it matches.

Note for us:  We should probably investigate ways to automatically detect stuff like this to make it easier on our users.

**Comment by v-ruizh** [comment]
Yes, the web page shows well after updating the port to the matched one. It would be better to add an option about port for deploy command.

**Comment by alexweininger** [comment]
Closing in favor of #310
