### ISSUE TITLE
Make managed environment activity delete description shorter

### ISSUE THREAD

**Issue by MicroFish91** [microsoft/vscode-azurecontainerapps#389]
<img width="1010" alt="image" src="https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/4d73f75f-dfbc-4062-a906-9e5136760d7d"> <br />

In general, I want to start making our activity descriptions shorter.  One idea is to remove the `Deleting Container Apps environment "mwf-3"` or at least shorten it to something simpler (e.g. `Deleting environment...` or similar) since this information is already shown in the activity title.

**Comment by nturinski** [comment]
It's a little bit complicated since the title is the name of the wizard, I believe. So while it works in this case, sometimes it will say "Creating Web App", but the description is set up to show all the steps that are running which is helpful to know.

I think the end goal should be that each step appears as a child underneath the title, which will make the description being too long to view less of an issue.

In this specific case though, we could probably just change the description to "This may take several minutes..." since the title does happen to match the step name.

**Comment by MicroFish91** [comment]
Yeah, I'm not so much worried about the title as I am the description, which we can control with the progress report message
