### ISSUE TITLE
Fail to execute "Deploy Image to Azure Container Apps..." action 

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurecontainerapps#488]
**OS:** All
**Build Version:** 20231012.1
**Regression:** Not a regression

**Repro Steps:**

1. Connect "Generic Registry V2" registry with URL "http://localhost:5100/".
2. Push one image to the above registry.
3. Expand the above registry -> Right click the image -> Select "Deploy Image to Azure Container Apps..." action -> Select a container app environment -> Select a container app.
4. Check whether succeeds to execute "Deploy Image to Azure Container Apps..." action.

**Actual:**
Fail to execute "Deploy Image to Azure Container Apps..." action.
![image](https://github.com/microsoft/vscode-docker/assets/107091828/07441b97-15b1-4731-9819-49da85e2d5d0)

**Suggestion:**
It would be better to remove "Deploy Image to Azure Container Apps..." action for the Generic Registry V2 registry.

**More Info:**
Succeeds to execute "Deploy Image to Azure App Service..." action for the Generic Registry V2 registry..

**Comment by alexyaang** [comment]
@MicroFish91 transferring this here as it's coming from the ACA extension.

**Comment by MicroFish91** [comment]
Hmm, it looks like we are getting that error thrown externally when we make the call out to update the container app.  The portal also has the same restriction: 

![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/af5933a6-771c-4aca-9eaa-0b96fc75347f)

Since this is just the secret reference name, is there any chance we could just strip out the `:` here to make it fit with what the service is expecting?  Otherwise I'm guessing we'd have to escalate this as an external issue.

**Comment by bwateratmsft** [comment]
I don't see why you couldn't strip out the `:`

**Comment by MicroFish91** [comment]
Yeah sure, I can do that

**Comment by v-chenzha** [comment]
Verified on the latest Azure Container Apps build 20231017.3 and released Docker extension v1.27.0 version, this issue still reproduces for now. The error message as below:
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/107091828/17547174-c700-4491-a9cc-9e7650a7feb7)
