### ISSUE TITLE
[Suggestion] Remove the extra step "Choose your source code directly" when building from project (the Dockerfile is not at the root) remotely using ACR 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurecontainerapps#591]
**OS:** All
**Build Version:** v0.6.2-alpha.0

**Repro Steps:**
1. Clone this repository https://github.com/Azure-Samples/containerapps-albumapi-javascript and open the project in VS Code.
2. Right click a container app environment -> Click "Create Container App..." -> Enter a name -> Select "Build from project remotely using Azure Container Registry" -> Select an azure container registry -> Choose the default Dockerfile.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/cab3f7df-3385-4a88-9b43-8f6965301508)
3. Check whether the next step is "Enter a name for the image" or not.

**Actual:**
The next step is "Choose your source code directly".
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/45614674/adea607b-1803-4f77-8f62-1b54f97d858c)

**Suggestion:**
Remove the extra step "Choose your source code directly" if the Dockerfile in the project is not at the root,

**Comment by MicroFish91** [comment]
I believe in this scenario since the Dockerfile is in the `./src` directory, so we need to prompt for the source code folder.  We basically have to prompt whenever the Dockerfile is _not_ in the root.

We have updated recently with this new format to choose your folders without browse as well which should be a nice improvement!

![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/40250218/1feae607-a60e-4ada-9662-2d8043da75bf)

Otherwise though, closing as by-design.
