### ISSUE TITLE
Fail to deploy an image to container app from Generic Registry V2

### ISSUE THREAD

**Issue by Amar-QA** [microsoft/vscode-azurecontainerapps#680]
**OS:** All
**Build Version**: 20240426.1
**Regression**: Not a regression

**Repro Steps:**

1. Connect "Generic Registry V2" registry with URL "http://localhost:5100/".
2. Push one image to the above registry.
3. Expand the above registry -> Right click the image -> Select "Deploy Image to Azure Container Apps..." action -> Select a container app environment -> Select a container app.
4. Check whether succeeds to execute "Deploy Image to Azure Container Apps..." action.

**Expect:**
Succeed to execute "Deploy Image to Azure Container Apps..." action.

**Actual:**
Fail to execute "Deploy Image to Azure Container Apps..." action.
![image](https://github.com/microsoft/vscode-azurecontainerapps/assets/156269329/ee7ccbc3-2992-422f-9fc6-ff9accde3161)

**Comment by MicroFish91** [comment]
What would the expected behavior be here?  

My initial thought is that since `localhost` is a relative URL pointing to self, if we provide this to the service, it makes sense that it would not be able to acquire the image.  I think I would only expect a successful retrieval if an absolute URL were provided 🤔
